def convert(number:int)->str:
    match number:
        case 5:
            return "V"
        case 10:
            return "X"
        case 50:
            return "L"
        case 100:
            return "C"
        case 500:
            return "D"
        case 1000:
            return "M"
        case _:
            return number*"I"